# Generated by Django 3.1 on 2022-09-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressuresensor',
            name='serial_number',
            field=models.CharField(default='989898', max_length=7, unique=True),
        ),
    ]
