# Generated by Django 3.1 on 2022-09-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0010_auto_20220918_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='row_value',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
    ]
