# Generated by Django 3.1 on 2022-09-18 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0011_sensorreading_row_value'),
    ]

    operations = [
         migrations.RunSQL("Update sensor_sensorreading set row_value=value;")
    ]
    
    
    
    
#     from django.db import migrations ,models

# def row_value_set(apps,schema_editor):
#     col=apps.get_model("sensor","sensorreading")
    
    
#     for val in col.objects.all():
#         val.row_value=val.value
#         val.save()
        
        
# class Migration(migrations.Migration):

#     dependencies = [
#         ('sensor', '0011_sensorreading_row_value'),
#     ]

#     operations = [
#         migrations.RunPython(row_value_set),
#     ]

