# Generated by Django 3.1 on 2022-10-01 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0012_auto_20220918_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensor.pressuresensor'),
        ),
    ]
