# Generated by Django 3.1 on 2022-10-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0013_auto_20221001_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='readingDate',
            field=models.DateTimeField(),
        ),
    ]
