# Generated by Django 3.1 on 2022-08-29 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pupDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 12, 6, 58, 913807), verbose_name='date published'),
        ),
    ]
