# Generated by Django 3.1 on 2022-09-11 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220829_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pupDate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
